name: Development Builds
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Build JavaScript package
        run: |
          yarn install
          yarn build
          yarn test
          yarn pack --filename stimulus-use-dev-build.tgz

      - name: Publish Dev Build
        run: |
          name="$(git log -n 1 --format=format:%cn)"
          email="$(git log -n 1 --format=format:%ce)"
          message="$(git log -n 1 --format=format:%s)"
          date="$(git log -n 1 --format=format:%ai)"

          tar -xf stimulus-use-dev-build.tgz

          git clone https://github.com/stimulus-use/dev-builds && cd dev-builds
          git remote remove origin
          git remote add origin https://${{ secrets.STIMULUSUSE_DEV_BUILDS_TOKEN }}@github.com/stimulus-use/dev-builds.git

          git checkout --orphan "${GITHUB_SHA:0:7}"
          cp -r ../package/. ./
          git add .

          git config --global user.name "$name"
          git config --global user.email "$email"

          GIT_COMMITER_DATE=${date} git commit -m "stimulus-use/${GITHUB_SHA:0:7} ${message}" --date "${date}"

          git tag stimulus-use/${GITHUB_SHA:0:7} -m "stimulus-use/${GITHUB_SHA:0:7} ${message}"
          git push origin stimulus-use/${GITHUB_SHA:0:7}
